### ISSUE TITLE
test failure in CI

### ISSUE THREAD

**Issue by werdahias** [brotskydotcom/dbus-secret-service#5]
dbus-secret service was packaged for Debian. Running its test-suite  in a chroot (via dbus-run-session -- cargo test ) causes  most tests to fail:
```

running 32 tests
dbus-daemon[19]: [session uid=1000 pid=19] Activating service name='org.freedesktop.secrets' requested by ':1.0' (uid=1000 pid=1199 comm="/tmp/tmp.EvsaVia5aC/target/x86_64-unknown-linux-gn")
GNOME_KEYRING_CONTROL=/home/unshare/.cache/keyring-A6WLU2
dbus-daemon[19]: [session uid=1000 pid=19] Successfully activated service 'org.freedesktop.secrets'
dbus-daemon[19]: [session uid=1000 pid=19] Activating service name='org.gnome.keyring.SystemPrompter' requested by ':1.16' (uid=1000 pid=1217 comm="/usr/bin/gnome-keyring-daemon --start --foreground")

(gcr-prompter:1224): Gtk-WARNING **: 15:56:55.228: cannot open display: 
dbus-daemon[19]: [session uid=1000 pid=19] Activated service 'org.gnome.keyring.SystemPrompter' failed: Process org.gnome.keyring.SystemPrompter exited with status 1
** Message: 15:56:55.231: couldn't initialize prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
** Message: 15:56:55.231: couldn't initialize prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
** Message: 15:56:55.231: couldn't initialize prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
test collection::test::should_check_if_collection_locked ... FAILED
test collection::test::should_get_all_items ... FAILED
test collection::test::should_search_items ... FAILED
test item::test::should_check_if_item_locked ... FAILED
test item::test::should_create_and_get_secret ... FAILED
test collection::test::should_create_collection_struct ... FAILED
test item::test::should_create_and_delete_item ... FAILED
test item::test::should_create_with_item_attributes ... FAILED
test item::test::should_get_and_set_item_label ... FAILED
test item::test::should_get_and_set_item_attributes ... FAILED
test collection::test::should_delete_collection ... FAILED
test collection::test::should_get_and_set_collection_label ... FAILED
test collection::test::should_lock_and_unlock ... FAILED
dbus-daemon[19]: [session uid=1000 pid=19] Activating service name='org.gnome.keyring.SystemPrompter' requested by ':1.16' (uid=1000 pid=1217 comm="/usr/bin/gnome-keyring-daemon --start --foreground")
test item::test::should_get_modified_created_props ... FAILED
test item::test::should_get_secret_content_type ... FAILED
test item::test::should_set_secret ... FAILED
test session::test::should_create_plain_session ... ok
test test::should_create_secret_service ... ok
test test::should_get_all_collections ... ok
test test::should_get_any_collection ... ok
test test::should_get_collection_by_alias ... ok
test test::should_get_default_collection ... FAILED

(gnome-keyring-daemon:1217): Gkm-CRITICAL **: 15:56:55.249: gkm_session_C_DestroyObject: assertion 'gkm_session_lookup_readable_object (self, handle, &object) == CKR_OBJECT_HANDLE_INVALID' failed

** (gnome-keyring-daemon:1217): WARNING **: 15:56:55.249: couldn't destroy credential object: Internal error
test test::should_search_items ... FAILED
test test::should_return_error_if_collection_doesnt_exist ... ok
test test::should_lock_and_unlock ... ok
test item::test::should_create_encrypted_item ... FAILED

(gcr-prompter:1239): Gtk-WARNING **: 15:56:55.257: cannot open display: 
dbus-daemon[19]: [session uid=1000 pid=19] Activated service 'org.gnome.keyring.SystemPrompter' failed: Process org.gnome.keyring.SystemPrompter exited with status 1
test item::test::should_create_and_get_secret_encrypted ... FAILED
** Message: 15:56:55.258: couldn't initialize prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
** Message: 15:56:55.258: couldn't initialize prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
test item::test::should_lock_and_unlock ... FAILED
test test::should_create_and_delete_collection ... FAILED
test item::test::should_create_encrypted_item_from_empty_secret ... FAILED
test item::test::should_get_encrypted_secret_across_dbus_connections ... FAILED
test session::test::should_create_encrypted_session ... ok

failures:

---- collection::test::should_check_if_collection_locked stdout ----
thread 'collection::test::should_check_if_collection_locked' panicked at src/collection.rs:146:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_check_if_collection_locked
             at ./src/collection.rs:146:26
   5: dbus_secret_service::collection::test::should_check_if_collection_locked::{{closure}}
             at ./src/collection.rs:144:43
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_get_all_items stdout ----
thread 'collection::test::should_get_all_items' panicked at src/collection.rs:186:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_get_all_items
             at ./src/collection.rs:186:26
   5: dbus_secret_service::collection::test::should_get_all_items::{{closure}}
             at ./src/collection.rs:184:30
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_search_items stdout ----
thread 'collection::test::should_search_items' panicked at src/collection.rs:193:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_search_items
             at ./src/collection.rs:193:26
   5: dbus_secret_service::collection::test::should_search_items::{{closure}}
             at ./src/collection.rs:191:29
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_check_if_item_locked stdout ----
thread 'item::test::should_check_if_item_locked' panicked at src/item.rs:153:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_check_if_item_locked
             at ./src/item.rs:153:26
   5: dbus_secret_service::item::test::should_check_if_item_locked::{{closure}}
             at ./src/item.rs:151:37
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_create_and_get_secret stdout ----
thread 'item::test::should_create_and_get_secret' panicked at src/item.rs:253:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_create_and_get_secret
             at ./src/item.rs:253:26
   5: dbus_secret_service::item::test::should_create_and_get_secret::{{closure}}
             at ./src/item.rs:251:38
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_create_collection_struct stdout ----
thread 'collection::test::should_create_collection_struct' panicked at src/collection.rs:139:45:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_create_collection_struct
             at ./src/collection.rs:139:17
   5: dbus_secret_service::collection::test::should_create_collection_struct::{{closure}}
             at ./src/collection.rs:137:41
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_create_and_delete_item stdout ----
thread 'item::test::should_create_and_delete_item' panicked at src/item.rs:140:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_create_and_delete_item
             at ./src/item.rs:140:26
   5: dbus_secret_service::item::test::should_create_and_delete_item::{{closure}}
             at ./src/item.rs:138:39
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_create_with_item_attributes stdout ----
thread 'item::test::should_create_with_item_attributes' panicked at src/item.rs:188:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_create_with_item_attributes
             at ./src/item.rs:188:26
   5: dbus_secret_service::item::test::should_create_with_item_attributes::{{closure}}
             at ./src/item.rs:186:44
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_get_and_set_item_label stdout ----
thread 'item::test::should_get_and_set_item_label' panicked at src/item.rs:175:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_get_and_set_item_label
             at ./src/item.rs:175:26
   5: dbus_secret_service::item::test::should_get_and_set_item_label::{{closure}}
             at ./src/item.rs:173:39
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- item::test::should_get_and_set_item_attributes stdout ----
thread 'item::test::should_get_and_set_item_attributes' panicked at src/item.rs:216:54:
called `Result::unwrap()` on an `Err` value: NoResult
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::item::test::should_get_and_set_item_attributes
             at ./src/item.rs:216:26
   5: dbus_secret_service::item::test::should_get_and_set_item_attributes::{{closure}}
             at ./src/item.rs:214:44
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_delete_collection stdout ----
thread 'collection::test::should_delete_collection' panicked at src/collection.rs:165:48:
called `Result::unwrap()` on an `Err` value: Prompt
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_delete_collection
             at ./src/collection.rs:165:9
   5: dbus_secret_service::collection::test::should_delete_collection::{{closure}}
             at ./src/collection.rs:163:34
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_get_and_set_collection_label stdout ----
thread 'collection::test::should_get_and_set_collection_label' panicked at src/collection.rs:227:70:
called `Result::unwrap()` on an `Err` value: Prompt
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_get_and_set_collection_label
             at ./src/collection.rs:227:26
   5: dbus_secret_service::collection::test::should_get_and_set_collection_label::{{closure}}
             at ./src/collection.rs:225:45
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- collection::test::should_lock_and_unlock stdout ----
thread 'collection::test::should_lock_and_unlock' panicked at src/collection.rs:155:14:
called `Result::unwrap()` on an `Err` value: Prompt
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /usr/src/rustc-1.80.1/library/core/src/result.rs:1102:23
   4: dbus_secret_service::collection::test::should_lock_and_unlock
             at ./src/collection.rs:153:26
   5: dbus_secret_service::collection::test::should_lock_and_unlock::{{closure}}
             at ./src/collection.rs:151:32
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
For now I opted to skip the ones that don't run but it would be nice if all test could run

**Comment by brotskydotcom** [comment]
Sorry to get back to you so late on this. It looks like you are running in a headless environment, so the KDE wallet cannot be unlocked (and the SystemPrompter failed). In order to get the tests to succeed in a headless environment, you have to arrange for the KDE wallet to be unlocked before the tests start. There is a lot of documentation around this in the [secret-service module of the keyring crate](https://docs.rs/keyring/3.4.0/keyring/secret_service/index.html#headless-usage). I should probably add this same doc to this crate!

**Comment by brotskydotcom** [comment]
I've pushed v4.0.3 which adds documentation around this issue.  If you're still having issues please comment here and I can investigate.
